---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: media
spec:
  chart:
    spec:
      chart: app-template
      version: 2.0.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 30m
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        statefulset:
          volumeClaimTemplates:
            - name: config
              accessMode: ReadWriteOnce
              size: 1Gi
              storageClass: ceph-block
              globalMounts:
                - path: /config

        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
            supplementalGroups:
              - 65539

        containers:
          main:
            image:
              repository: ghcr.io/bjw-s/calibre-web
              tag: 0.6.21@sha256:dd8d0aad904027c6dbcece2f919770f39cc2e3983fdab0d4df437ace346e8a55
            env:
              CACHE_DIR: /cache
            resources:
              requests:
                cpu: 5m
                memory: 470M
              limits:
                memory: 470M

    service:
      main:
        ports:
          http:
            port: 8083

    ingress:
      main:
        enabled: true
        className: internal-nginx
        annotations:
          nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-internal-proxy-outpost.security.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: /outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host calibre-web.bjw-s.dev
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      media:
        type: nfs
        server: nas.bjw-s.casa
        path: /volume1/Media
        globalMounts:
          - path: /data/nas-media
      cache:
        type: emptyDir
        globalMounts:
          - path: /cache
